version: "3"
services:
  app:
    build: ./
    depends_on:
      - db
      - jaeger
    ports:
      - 9000:9000
  db:
    image: mysql:8.0.27
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - dbdata:/var/lib/mysql/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3306:3306
  jaeger:
    image: jaegertracing/all-in-one:1.27
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
  prometheus:
    image: prom/prometheus:v2.27.1
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - ./monitoring/prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana-data:/var/lib/grafana
      - ./monitoring/grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=admin
volumes:
  dbdata:
    driver: local
